### ISSUE TITLE
Changing `wt.homedir.root` breaks existing DirectFSAssetstore

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/wt_home_dirs#3]
Right now it just dies with:

```
ERROR: Failed to load plugin "wt_home_dir":
Traceback (most recent call last):
  File "/girder/girder/utility/plugin_utilities.py", line 115, in loadPlugins
    root, appconf, apiRoot = loadPlugin(plugin, root, appconf, apiRoot)
  File "/girder/girder/utility/plugin_utilities.py", line 246, in loadPlugin
    pluginLoadMethod(info)
  File "/girder/plugins/wt_home_dir/server/__init__.py", line 67, in load
    provider = WTFilesystemProvider(homeDirsRoot)
  File "/girder/plugins/wt_home_dir/server/lib/WTFilesystemProvider.py", line 159, in __init__
    self.updateAssetstore()
  File "/girder/plugins/wt_home_dir/server/lib/WTFilesystemProvider.py", line 168, in updateAssetstore
    'WT Home Dirs', self.rootFolderPath)
  File "/girder/girder/models/assetstore.py", line 146, in createDirectFSAssetstore
    'perms': perms
  File "/girder/girder/models/model_base.py", line 418, in save
    document = self.validate(document)
  File "/girder/girder/models/assetstore.py", line 44, in validate
    'exists.', 'name')
girder.exceptions.ValidationException: An assetstore with that name already exists.
```

This is of course caused by my naive implementation of relation between WsgiDAV server and Girder's assetstore.

**Comment by Xarthisius** [comment]
Obsoleted by #6
